### ISSUE TITLE
Authentication Evidence - definition

### ISSUE THREAD

**Issue by per-mutzell** [oidc-sweden/specifications#10]
Can see the use case for the claim AuthenticationEvidence, but will it be practically useful with this very loose type definition?
Maybe better to limit the scope and definition of more precise claims, 
authnEvidenceOCSP or something like that?

**Comment by martin-lindstrom** [comment]
I am not sure that I agree. The contents may be decided by the context in which the claim is used, and we really don't want to introduce too many claims with specific usage.

**Comment by per-mutzell** [comment]
I agree that we want to avoid specific usage if possible. Maybe it is possible to define a common format that is in itself described / typed. Thinking about JWT-format for the claim or something in that neighborhood.

**Comment by martin-lindstrom** [comment]
Look at KYC ...
