### ISSUE TITLE
Two or three signature models?

### ISSUE THREAD

**Issue by PetterBID** [oidc-sweden/specifications#11]
You could consider a third alternative  when the Signature Service are behind the OpenID Proveder?  (For the OpenID Provider that delegate its signing to a Signature Service)

**Comment by martin-lindstrom** [comment]
The model of federated signing is that a Signature Service uses an identity provider (SAML or OIDC) to authenticate the user for signing. So in your case an OpenID Provider would state that it supports signing, and then act as a relying party to a signature service, which later uses another OpenID Provider to authenticate the user for signature. I think that would fit into the two existing models.
