### ISSUE TITLE
Signature Extension: clarifications regarding signMessageDigest

### ISSUE THREAD

**Issue by eriklupander** [oidc-sweden/specifications#12]
Two things regarding `https://claims.oidc.se/1.0/signMessageDigest`:

* The spec states `A digest of the sign message that was sent by the client in the request.` Is it necessary to explicitly specify whether the digest should be computed on the `base64` representation of `message` or its clear-text representation?
* Should the spec. define the format of the digest? I.e. base64-representation of the raw digest bytes or similar?

**Comment by eriklupander** [comment]
Note: Found the details in `3.2.4. The signMessageDigest Attribute` from Sweden Connect technical framework. So it's more a question on whether to let the oidc-sweden specification explicit state the requirements or refer to Sweden Connect?

**Comment by martin-lindstrom** [comment]
Yes. I don't think that we should refer too much to a bunch of SAML specifications. I'll make sure that our OIDC-specs are stand-alone...
