### ISSUE TITLE
Signature Extension: Possible need of clarification for 3.2.1.2

### ISSUE THREAD

**Issue by eriklupander** [oidc-sweden/specifications#13]
`3.2.1.2. Placed in a Request Object` states: `Note: It is perfectly legal to create a request where some parameters are assigned as regular request parameters and some are included in the Request Object`.

The requirements states that a Request Object containing a signRequest MUST be signed. This implicitly means that the _signRequest_ must be used in its entirely. Could (perhaps novice) implementors become confused and believe that part of signRequest from a request object may be used to "override" values from a (likewise signed) signRequest JWT passed as custom query parameter? For example, that a `mime_type` specified in the request objects `signRequest` would override the `mime_type` from the custom request parameter JWT?

Of course, it doesn't make sense given the signed nature of request objects / custom request parameter JWT for `signRequest`, but I believe it's a possible source of confusion given the "Note" and how parameters can be overridden using request objects.

**Comment by martin-lindstrom** [comment]
The core OIDC specification clearly states that any parameters given in a RequestObject overrides any ordinary request parameters, so, if you supply for example `nonce` both as a regular request parameter and as a field in a RequestObject it is the one in the RequestObject that should be used.

There will be many ways to get things wrong, but I'll add an extra "note" about this.
