### ISSUE TITLE
3.1.1.2 client_secret_basic + mTLS - own identifier?

### ISSUE THREAD

**Issue by eriklupander** [oidc-sweden/specifications#21]
Regarding Mutual TLS + `client_secret_basic`: Do we want a profile-specific identifier for this particular type of client authentication?

Something along the lines of: `https://auth.oidc.se/1.0/client_secret_basic_mtls`

From the top of my head I can't recall seeing the standard client authentication methods in actual requests or responses, so probably not necessary from a technical / interoperability point-of-view. However, could it be beneficial from an intelligibility perspective to let the OIDC Swedish profile formally define a custom `client authentication` for mTLS + client_secret_basic?

Edit: Translated into english

**Comment by martin-lindstrom** [comment]
I've made a change where we eased up the requirements. Mutual TLS is now mentioned, but only as a possible solution outside of the scope of the profile.
