### ISSUE TITLE
Discuss of how to handle login_hint and how the RP should communicate a known user ID

### ISSUE THREAD

**Issue by martin-lindstrom** [oidc-sweden/specifications#3]
In section 3.1.2.1 of [OpenID Connect Core 1.0](https://openid.net/specs/openid-connect-core-1_0.html) the `login_hint` request parameter is described. This is defined as:

> Hint to the Authorization Server about the login identifier the End-User might use to log in (if necessary). This hint can be used by an RP if it first asks the End-User for their e-mail address (or other identifier) and then wants to pass that value as a hint to the discovered authorization service. It is RECOMMENDED that the hint value match the value used for discovery. This value MAY also be a phone number in the format specified for the phone_number Claim. The use of this parameter is left to the OP's discretion.

For BankID and Freja eID the personal identity number in some cases are supplied from the RP to the server. We **could** do this using the `login_hint` parameter, but this will not be a sustainable solution since just about anything may be added to this parameter.

A more general solution (especially for use within a federation) is to use a Request Object JWT where a list of name-value pairs is supplied (where the name is the claim name and the value is the claim value). See [Principal Selection in SAML Authentication Requests](https://docs.swedenconnect.se/technical-framework/latest/14_-_Principal_Selection_in_SAML_Authentication_Requests.html).

**Comment by martin-lindstrom** [comment]
But we should keep in mind that in the case of using BankID or Freja in a OIDC context, the RP is no longer responsible of the UI. This is done by the OP (IdP), so the prompting for the personal identity number will be done by the OP.

However, there are still many cases when the RP already knows the identity of the user, for example when asking an already logged in user to sign something, or when the RP wants the user to re-authenticate.

**Comment by martin-lindstrom** [comment]
An obvious way to achieve this is to use the `claims` parameter in the request and set a value. For example:

```
{
  "id_token" : {
    "http://claims.oidc.se/personalNumber" : { "essential" : "true", "value" : "191212121212" }
  }
}
```

This tells the OP that the RP wants a `http://claims.oidc.se/personalNumber` claim that holds the value 191212121212.

See section 5.5, "Requesting Claims using the "claims" Request Parameter", of [OpenID Connect Core 1.0](https://openid.net/specs/openid-connect-core-1_0.html#ClaimsParameter).

**Comment by per-mutzell** [comment]
I agree that the right way of doing this is according to section 5.5, "Requesting Claims using the "claims" Request Parameter", of OpenID Connect Core 1.0, specifying "value" if needed as in your example.
In the specification right now we have chap 2.5 "Request Object Claims" (Specific claims that are sent in a Request Object), and I am not sure that this approach is needed at all if we use the technique above.
