### ISSUE TITLE
Remove use of login_hint

### ISSUE THREAD

**Issue by Razumain** [oidc-sweden/specifications#48]
The more I read OIDC-core, the more I'm convinced that the `login_hint` is meant to provided the user ID part for cases where the user is authenticated with id/password or similar.

" _Hint to the Authorization Server about the login identifier the End-User might use to log in_".

In the current specification we sort of allow both the use of this parameter AND the `claims` parameter  to specify the id of the user we expect to authenticate, even if the latter is recommended. I think this introduce a risk for confusion and interoperability problems.

I don't think we should imply that the use of `login_hint` and claims with value parameter are alternatives, one being recommended and the other optional. I think we should settle on one alternative specifying a distinct expected claims value.

Perhaps the best solution is to only talk about the use of the `claims` request parameter to specify that a user with a specific claims value is expected, and to leave the login_hint out of the specification (or just have a note clarifying that it is NOT the parameter to use for this purpose).

**Comment by martin-lindstrom** [comment]
We already point out that the `claims`-parameter should be used in favour of `login_hint`.

**Comment by martin-lindstrom** [comment]
I will re-phrase the text so people don't get confused.
