### ISSUE TITLE
Adding age to Natural Person Name Information

### ISSUE THREAD

**Issue by vedrnes** [oidc-sweden/specifications#6]
Many services have age restrictions rather than the need to explicitly know the personal number or birthday of an individual. Perhaps adding age as an optional attribute to the Natural Person Name Information scope would allow the delivery of such information, if available, by an IdP.

**Comment by martin-lindstrom** [comment]
First of all we need to make sure that there is a claim defined for age. I don't think that there is a standard one to use.

I am not sure that I agree that age should be part of the "Natural Person Name Information" scope. In many cases age is of no interest, and we need to ensure to not define scopes that deliver too much information. But I agree, and understand, the need for it. Perhaps it is better to define a scope, "Natural Person Identity - Age" for this purpose?

Also. A claim can always be explicitly requested

**Comment by vedrnes** [comment]
I agree, a different scope could be the way to provide age because delivering age rather than civic registration number or birthday certainly has a practical use. Now that we are already here, the information contained in Natural Person Name is a subset of the standard *profile* scope that all OIDC clients support and understand meaning that future integration would be simpler, no special mappings would be required on the client side. Is it the fact that claims in the *profile* scope are optional that has led to the inclusion of Natural Person Name or is it something else?

**Comment by martin-lindstrom** [comment]
I would say that it is of privacy reasons since `profile` contains a little bit too much information.

**Comment by vedrnes** [comment]
Along the similar line of protecting the privacy of the individual, apart from returning the actual age, it would also make sense to have a way to "condition" an authentication with age. Not sure whether it is possible, but a service would send "minimum required age" as part of authentication request, the IdP responds positively only if age is >= than that specified without exposing the actual age (or even less so, birthday) of the end-user.

**Comment by vedrnes** [comment]
I understand your concerns. On the other hand, practically all IdPs with LoA3 assurance in Sweden have at least established a connection between an individual and civic registration number (personnummer) and most likely also a date of birth given that the latter cannot be accurately determined from the former. What I am suggesting here is a mechanism whereby a service that needs to establish the age of individuals logging in but does not really need to know the civic registration number or actual birthday has a way of requesting this. Sort of, you need to be over 15 to play some game online - the game does not really need to know your civic registration number.
In terms of the information being accurate, I would certainly expect the age information to be up to date upon each authentication - if the IdP has established the date of birth for the person being authenticated that is not an issue.
