### ISSUE TITLE
Claims released in the ID Token 

### ISSUE THREAD

**Issue by rohe** [oidc-sweden/specifications#62]
In Swedish-oidc-profile.md the following sentence appear:

"Therefore, this profile, requires that if any of the scopes defined in section 3 of [[OIDC.Sweden.Attr](https://github.com/oidc-sweden/specifications/issues/new#attr-spec)] are requested the corresponding claims MUST be delivered in the ID token"

This I think is very problematic demand since it means that no standards compliant OP software can be used out-of-the-box, in federations that adheres to this specification, without modifications.

If you want to make it easy for people to use the specification this is not the way to go.

The standards compliant alternative would be to combine scope with usage of the claim parameter in the authorization request.

**Comment by martin-lindstrom** [comment]
Yes. We need to re-think this.
