### ISSUE TITLE
Consider using claims defined in "OpenID Connect for Identity Assurance 1.0"

### ISSUE THREAD

**Issue by martin-lindstrom** [oidc-sweden/specifications#63]
[OpenID Connect for Identity Assurance 1.0](https://openid.net/specs/openid-connect-4-identity-assurance-1_0-13.html) defines some claims that we also are defining in our "Attribute Specification". These are:

- `place_of_birth` - `https://id.oidc.se/claim/placeOfbirth`. A structured JSON object instead of our version that is a string.
- `birth_family_name`, `birth_given_name` and `birth_middle_name` - Corresponding to "our" `https://id.oidc.se/claim/birthName` claim.

[OpenID Connect for Identity Assurance 1.0](https://openid.net/specs/openid-connect-4-identity-assurance-1_0-13.html)
also defines the `nationalities` claim that is a string array representing the End-User's nationalities. We define a more generic country-claim, and we may want to remove that definition as well. However, there are more circumstances where we may want to represent a country other than to represent a nationality (in eIDAS for example). 

I suggest that we remove our definitions (while still in draft mode).

**Comment by leifj** [comment]
Does it even make sense to focus our efforts on complex attributes that will be part of the wallet anyway?

**Comment by martin-lindstrom** [comment]
No, it doesn't. I was just given access to the PID Rule Book for the EUDI Wallet ecosystem, and when browsing it I see that we could get rid of some of our other "private" claims as well.

**Comment by martin-lindstrom** [comment]
We should not define any of the "general purpose claims". They just don't belong to our spec.
