### ISSUE TITLE
authentication request parameter encoding clarifications

### ISSUE THREAD

**Issue by Razumain** [oidc-sweden/specifications#67]
When a request parameter contains a structured JSON object, such as the "claims" parameter and the https://id.oidc.se/param/userMessage parameter, we should clarify the encoding strategy when passed as a URL parameter as well as when it is provided in a request JWT

When the json object is provided as a URL parameter, it is quite obvious that is must be URL encoded such as:

`claims=%7B%22userinfo%22%3A%7B%22https%3A%5C%2F%5C%2Fid.oidc.se%5C%2Fclaim%5C%2FpersonalIdentityNumber%22%3A%7B%22essential%22%3Atrue%7D%2C%22https%3A%5C%2F%5C%2Fid.oidc.se%5C%2Fclaim%5C%2FcoordinationNumber%22%3Anull%2C%22birthdate%22%3Anull%2C%22name%22%3A%7B%22essential%22%3Atrue%7D%2C%22given_name%22%3A%7B%22essential%22%3Atrue%7D%2C%22family_name%22%3A%7B%22essential%22%3Atrue%7D%7D`

However, when passed inside a request JWT (or request_uri), the value is included as a JSON object:

```
{
    "userinfo": {
        "https://id.oidc.se/claim/personalIdentityNumber": {"essential": true},
        "https://id.oidc.se/claim/coordinationNumber": null,
        "birthdate": null,
        "name": {"essential": true},
        "given_name": {"essential": true},
        "family_name": {"essential": true}
    }
}
```

White space and line breaks included for illustration only.

This is obvious from the examples in the OIDC core specification, but as this has demonstrated to cause Interop problems, it would benefit from clarification in the profile.

**Comment by leifj** [comment]
This is clearly a bug in the base specification and should be handled "upstream" instead of in a Swedish profile. I would argue that even if the intent is good, the result of "fixing" the issue in our profile will eventually lead to profile diverging from the base spec.

**Comment by martin-lindstrom** [comment]
Section 6.1 of OIDC code gives examples of this.
