### ISSUE TITLE
iss and aud claims in JWT request 

### ISSUE THREAD

**Issue by Razumain** [oidc-sweden/specifications#68]
OIDC core is not very precise with regard to iss and aud claims in JWT request data:

`If signed, the Request Object SHOULD contain the Claims iss (issuer) and aud (audience) as members. The iss value SHOULD be the Client ID of the RP, unless it was signed by a different party than the RP. The aud value SHOULD be or include the OP's Issuer Identifier URL.`

This has cased some issues in Interop tests. We should consider two things:

1) Whether the presence of iss and aud should be upgraded to MUST in our profile where iss MUST be the ClientID
2) Whether we should limit the valid aud values further to either the OP issuer identity or the OP authorization endpoint URL.

On issue 2 my proposal is:
The aud value SHOULD be the OP authorization endpoint URL. The aud value MUST NOT include any value other than the OP authorization endpoint URL or the Issuer Identifier URL.

**Comment by martin-lindstrom** [comment]
I don't think it is a bug in the core spec. The core spec. is (deliberately) vague concerning these issues.

As long as we state the an OP SHOULD be prepared to receive an audience value according to what is written in the core spec, and state that an RP SHOULD use the OP issuer ID, we are home free and don't diverge.

**Comment by peppelinux** [comment]
`aud` is required for security reason, as jti to `avoid` replay
`sub` must not included to prevent that a request object could be reused as a private_key_jwt (`client_assertion`)

the `iss` of the JWT is the RP and must be equal to `client_id`
