### ISSUE TITLE
Personal Identity Number -> Civic Registration Number

### ISSUE THREAD

**Issue by vedrnes** [oidc-sweden/specifications#7]
I find "Civic Registration Number" to be a better interpretation of "personnummer" than "Personal Identity Number". Plus that the latter can be abbreviated to PIN leading to all sorts of confusions, whilst the former results in CRN which is less prone to misinterpretation.
I therefore propose that the corresponding claim be changed to http://claims.oidc.se/1.0/civicRegistrationNumber

**Comment by martin-lindstrom** [comment]
Let's discuss this further at the meeting ...

**Comment by martin-lindstrom** [comment]
The Swedish Tax Authorithy, that "owns" the Swedish "personnummer", uses “personal identity number” in he brochure
"Population registration in Sweden SKV 717B", so I suggest that we stick with that.
