### ISSUE TITLE
Cancel processing and error code

### ISSUE THREAD

**Issue by Razumain** [oidc-sweden/specifications#71]
The current profile suggest that cancel by user cause the return of:

1. error = access_denied
2. error_description starting with "user-cancel"

This is a less ideal solution because description is often provided in local language and it is often problematic to include machine parseable code into text description strings.

I think we probably need a new error code here like "user-cancel". I can't really see the interop problems this would create. In the worst case the RP will not be able to process the error code and will not be able to properly handle the error. But that will also be the case if the RP use standard mechanisms to process "access-denied".

In a way it would be worse to use an existing error code outside of its intended purpose, as it may lead to confusing error messages shown to the user.

**Comment by martin-lindstrom** [comment]
I agree that it is frustrating that OIDC (and SAML) do not have a specific error code for user cancel, but I don't think that it is up to us to fix it. We simply cannot introduce any new error codes at this level.

And. Using `access_denied` here is what other OP:s do. It simply means "The user has denied the RP access to its identity claims", and that's what's happening. OK, there may be other cases where `access_denied` will be used, but I think that if an RP received `access_denied` as a response to an authentication request it is pretty safe to assume "cancel".

**Comment by Razumain** [comment]
I'm a bit worried still that some RP of Sweden Connect has a specific UI flow for cancel that they expect to work also with an OP, not only for SAML IdP:s. But then that is a question for Sweden Connect and not the general national profile.

**Comment by per-mutzell** [comment]
I checked Ineras IdP and for SAML SPs there is no specific error code for user cancel (just AuthnFailed) and I do think it is the same for OIDC, but have to check that cause it was a bit hidden for me right now.

Generally I agree that we should not introduce a custom err code outside the core spec if not absolutely necessary, and we should avoid introduce sub-codes in the description fields, they will be too tempting to use and then things can break in the future.

**Comment by per-mutzell** [comment]
Now I have checked the OIDC implementation at Inera. There is indeed a specific error code for user cancel ("user_cancel"). How important this is is a bit unclear for me though.

**Comment by martin-lindstrom** [comment]
Just an idea. If both Inera:s federation and Sweden Connect see the need for a custom error code representing "user cancelled the authentication", it may be a good thing to define it in the OIDC Sweden context (to make sure we get interoperability between federations that see the need for it). We wouldn't be able to require support for the custom error code, but it would be defined. 

Also, we could have a special purpose OP metadata field, `user_cancel_code_supported`, as well.
