### ISSUE TITLE
Preferred authentication provider for better user experience

### ISSUE THREAD

**Issue by per-mutzell** [oidc-sweden/specifications#8]
"2.3. Authentication Information Claims"

I can see the need for authentication related attributes that can support a more user friendly experience when using IdP:s for autentication.  
This applies to (at least) the flows authentication for sign and forced (re-)authentication . 
Find this also useful to bridge between different used IdP-concepts:  "one IdP - one authentication method", "one IdP - multiple authentication methods" and IdP-proxy solutions (one IdP - multiple IdP's and authentication methods)
Also CGI has mentioned the need for this in conjunction with signature services.

**An example scenario:** 
A service provider SP uses an IdP that provides multiple authentication methods.
	The SP provides 1) digital signing of documents by means of a separate Signing service  2) sensitive operations that requires the user to re-authenticate in the session.
The user logs into the SP and chooses a one of the possible authentication methods.
	When the user is prompted again to authenticate (either in the case of re-auth or signing), the user (if possible) should not have to make the choice of  authentication method again.
	
A solution to this: the IdP provides separate endpoints (locigal IdP's) for each authentication method, besides the endpoint that provides a choice of authentication methods.
To be able to forward the user to the same (preferred) authentication method the SP needs information about the initial authentication.
	
**Proposal**
Maybe optional authentication information claims are added to support these use cases, for example:
_PreferredAuthenticationProvider_ [URL]
_PreferredAuthenticationProviderForSign_ [URL]
(or some other logical names)
	
SP:s can choose to use these or not depending on what user experience they need to implement.

Comment:
Rationale for able to provide a separate AuthenticationProviderForSign: when implementing the technical framework for federated digital signatures (extensions, attribute spec, deploy profile …) in an existing IdP solution, it can be very complicated to superimpose these requirements on top of preexisting requirements using the same endpoint. In our experience it can be a lot easier to implement a separate endpoint for the sign flow that compliments the endpoint for ordinary authentication.

**Comment by martin-lindstrom** [comment]
We are developing a generic set of specifications so I am a bit reluctant to add something too specific such as PreferredAuthenticationProviderForSign. But, in the generic case, we need to discuss Proxy-IdP:s. SAML has the elements `AuthenticatingAuthority` and `Scopes/IDPList` that are handy when using proxy-IdP:s. Let's see if we can find something similar for OpenID Connect.

**Comment by martin-lindstrom** [comment]
Leif will investigate proxy solutions ...
