### ISSUE TITLE
credentialPolicy

### ISSUE THREAD

**Issue by per-mutzell** [oidc-sweden/specifications#9]
I can see use cases where a Service Provider needs information about the specific issuing policy for the credential used for authentication. For certificates this would normally correspond to the Policy Identifier OID.

I therefore propose a authentication information claim for this, for example:
credentialPolicy
Description: Issuing policy identifier for the users credential
Type: maybe URI? (support for OID, URL)

**Comment by martin-lindstrom** [comment]
> Since you joined a bit later. Just a comment about "we". The group decided that the participants of the working group are there as individual experts, and we refrain from using our respective organizations in the communication.

About the comment. Yes, it may be a good idea to have a generic policy for an authentication. Let's discuss this at the next meeting.

**Comment by martin-lindstrom** [comment]
VOT candidate?

**Comment by martin-lindstrom** [comment]
I think should be covered by the `userCertificate` claim where the RP can find any policy identifiers it wishes to check. A specific claim for this will lead the generic profile into a path where it shouldn't be. Discussing policies and such are out of scope for this profile.
